// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniSupermarket.API.Data;

#nullable disable

namespace MiniSupermarket.API.Migrations
{
    [DbContext(typeof(SupermarketDbContext))]
    [Migration("20261008104240_AddUserSeed")]
    partial class AddUserSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Nước giải khát",
                            Description = "Nước ngọt, nước tăng lực, nước khoáng"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Sữa & sản phẩm từ sữa",
                            Description = "Sữa tươi, sữa hộp, sữa chua"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Bánh kẹo",
                            Description = "Bánh quy, kẹo, socola"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Đồ ăn vặt",
                            Description = "Snack, rong biển, đồ ăn nhẹ"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Mì & thực phẩm ăn liền",
                            Description = "Mì gói, phở, cháo ăn liền"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Gạo & thực phẩm khô",
                            Description = "Gạo, đậu, các loại hạt"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Gia vị & dầu ăn",
                            Description = "Nước mắm, nước tương, dầu ăn"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Thực phẩm đóng hộp",
                            Description = "Cá hộp, thịt hộp, pate"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Đồ uống dinh dưỡng",
                            Description = "Sữa hạt, nước yến, thức uống dinh dưỡng"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Cà phê & trà",
                            Description = "Cà phê hòa tan, cà phê gói, trà"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Hóa mỹ phẩm",
                            Description = "Dầu gội, sữa tắm, sản phẩm chăm sóc cơ thể"
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Chăm sóc cá nhân",
                            Description = "Kem đánh răng, khăn giấy, khẩu trang"
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "Đồ dùng gia đình",
                            Description = "Nước rửa chén, túi rác, đồ dùng gia đình"
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = "Văn phòng phẩm",
                            Description = "Bút, vở, dụng cụ học tập"
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryName = "Đồ dùng tiện ích",
                            Description = "Pin, bật lửa và các vật dụng tiện ích"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MembershipRank")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "15 Đường Thành Thái, Phường 12, Quận 10, TP.HCM",
                            CustomerName = "Nguyễn Văn An",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0901122334",
                            RewardPoints = 850
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "28 Đường Võ Văn Tần, Phường 6, Quận 3, TP.HCM",
                            CustomerName = "Trần Thị Bình",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0918877665",
                            RewardPoints = 520
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "42 Đường Nguyễn Trãi, Phường 3, Quận 5, TP.HCM",
                            CustomerName = "Lê Văn Cường",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0983344556",
                            RewardPoints = 120
                        },
                        new
                        {
                            CustomerId = 4,
                            Address = "56 Đường Nguyễn Huệ, Phường Bến Nghé, Quận 1, TP.HCM",
                            CustomerName = "Phạm Thị Dung",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0934567812",
                            RewardPoints = 1250
                        },
                        new
                        {
                            CustomerId = 5,
                            Address = "73 Đường Lãnh Binh Thăng, Phường 12, Quận 11, TP.HCM",
                            CustomerName = "Hoàng Minh Đức",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0978123456",
                            RewardPoints = 320
                        },
                        new
                        {
                            CustomerId = 6,
                            Address = "91 Đường Cộng Hòa, Phường 4, Quận Tân Bình, TP.HCM",
                            CustomerName = "Võ Thị Hạnh",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0908765432",
                            RewardPoints = 90
                        },
                        new
                        {
                            CustomerId = 7,
                            Address = "36 Đường Xô Viết Nghệ Tĩnh, Phường 21, Quận Bình Thạnh, TP.HCM",
                            CustomerName = "Đặng Quốc Huy",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0912345678",
                            RewardPoints = 680
                        },
                        new
                        {
                            CustomerId = 8,
                            Address = "108 Đường Quang Trung, Phường 10, Quận Gò Vấp, TP.HCM",
                            CustomerName = "Bùi Ngọc Lan",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0987654321",
                            RewardPoints = 1580
                        },
                        new
                        {
                            CustomerId = 9,
                            Address = "64 Đường Phan Đình Phùng, Phường 2, Quận Phú Nhuận, TP.HCM",
                            CustomerName = "Nguyễn Thị Mai",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0945678123",
                            RewardPoints = 210
                        },
                        new
                        {
                            CustomerId = 10,
                            Address = "125 Đường Lê Trọng Tấn, Phường Sơn Kỳ, Quận Tân Phú, TP.HCM",
                            CustomerName = "Trương Minh Nam",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0961234789",
                            RewardPoints = 760
                        },
                        new
                        {
                            CustomerId = 11,
                            Address = "39 Đường Hậu Giang, Phường 5, Quận 6, TP.HCM",
                            CustomerName = "Phan Thị Oanh",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0903456789",
                            RewardPoints = 1800
                        },
                        new
                        {
                            CustomerId = 12,
                            Address = "82 Đường Nguyễn Thị Thập, Phường Tân Quy, Quận 7, TP.HCM",
                            CustomerName = "Đỗ Hoàng Phúc",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0973456128",
                            RewardPoints = 60
                        },
                        new
                        {
                            CustomerId = 13,
                            Address = "47 Đường Võ Văn Ngân, Phường Linh Chiểu, TP. Thủ Đức, TP.HCM",
                            CustomerName = "Lý Minh Quân",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0937894561",
                            RewardPoints = 430
                        },
                        new
                        {
                            CustomerId = 14,
                            Address = "116 Đường Tên Lửa, Phường Bình Trị Đông B, Quận Bình Tân, TP.HCM",
                            CustomerName = "Nguyễn Ngọc Thảo",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0915678234",
                            RewardPoints = 1020
                        },
                        new
                        {
                            CustomerId = 15,
                            Address = "53 Đường Nguyễn Văn Quá, Phường Đông Hưng Thuận, Quận 12, TP.HCM",
                            CustomerName = "Trần Minh Tú",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0981234567",
                            RewardPoints = 150
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Barcode = "8938505970011",
                            CategoryId = 1,
                            Price = 6000m,
                            ProductName = "Nước suối Aquafina 500ml",
                            StockQuantity = 120
                        },
                        new
                        {
                            ProductId = 2,
                            Barcode = "8935049500028",
                            CategoryId = 1,
                            Price = 10000m,
                            ProductName = "Coca Cola lon 330ml",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 3,
                            Barcode = "8934673700035",
                            CategoryId = 2,
                            Price = 7500m,
                            ProductName = "Sữa tươi Vinamilk 180ml",
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductId = 4,
                            Barcode = "8934680030042",
                            CategoryId = 3,
                            Price = 22000m,
                            ProductName = "Bánh Oreo vị chocolate 133g",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 5,
                            Barcode = "8934572900059",
                            CategoryId = 4,
                            Price = 18000m,
                            ProductName = "Snack khoai tây Lay's 95g",
                            StockQuantity = 70
                        },
                        new
                        {
                            ProductId = 6,
                            Barcode = "8934563150066",
                            CategoryId = 5,
                            Price = 4500m,
                            ProductName = "Mì Hảo Hảo tôm chua cay",
                            StockQuantity = 150
                        },
                        new
                        {
                            ProductId = 7,
                            Barcode = "8938505970073",
                            CategoryId = 6,
                            Price = 145000m,
                            ProductName = "Gạo ST25 túi 5kg",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 8,
                            Barcode = "8934588010080",
                            CategoryId = 7,
                            Price = 32000m,
                            ProductName = "Nước mắm Nam Ngư 500ml",
                            StockQuantity = 45
                        },
                        new
                        {
                            ProductId = 9,
                            Barcode = "8934564700097",
                            CategoryId = 8,
                            Price = 28000m,
                            ProductName = "Cá ngừ đóng hộp 170g",
                            StockQuantity = 35
                        },
                        new
                        {
                            ProductId = 10,
                            Barcode = "8934673200103",
                            CategoryId = 10,
                            Price = 42000m,
                            ProductName = "Cà phê hòa tan G7 3in1",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 11,
                            Barcode = "8935217100110",
                            CategoryId = 11,
                            Price = 89000m,
                            ProductName = "Dầu gội Sunsilk 650g",
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductId = 12,
                            Barcode = "8935001700127",
                            CategoryId = 12,
                            Price = 38000m,
                            ProductName = "Kem đánh răng P/S 180g",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 13,
                            Barcode = "8934868000134",
                            CategoryId = 13,
                            Price = 35000m,
                            ProductName = "Nước rửa chén Sunlight 750ml",
                            StockQuantity = 55
                        },
                        new
                        {
                            ProductId = 14,
                            Barcode = "8938501230141",
                            CategoryId = 14,
                            Price = 18000m,
                            ProductName = "Vở học sinh 200 trang",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 15,
                            Barcode = "8936001250158",
                            CategoryId = 15,
                            Price = 45000m,
                            ProductName = "Pin AA Panasonic 4 viên",
                            StockQuantity = 20
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            FullName = "Nguyễn Quản Trị",
                            IsActive = true,
                            PasswordHash = "123456",
                            Role = "Admin",
                            Username = "admin01"
                        },
                        new
                        {
                            UserId = 2,
                            FullName = "Trần Giám Đốc",
                            IsActive = true,
                            PasswordHash = "123456",
                            Role = "Admin",
                            Username = "admin02"
                        },
                        new
                        {
                            UserId = 3,
                            FullName = "Lê Thu Ngân",
                            IsActive = true,
                            PasswordHash = "123456",
                            Role = "Cashier",
                            Username = "cashier01"
                        },
                        new
                        {
                            UserId = 4,
                            FullName = "Phạm Bán Hàng",
                            IsActive = true,
                            PasswordHash = "123456",
                            Role = "Cashier",
                            Username = "cashier02"
                        },
                        new
                        {
                            UserId = 5,
                            FullName = "Hoàng Thu Ngân",
                            IsActive = true,
                            PasswordHash = "123456",
                            Role = "Cashier",
                            Username = "cashier03"
                        },
                        new
                        {
                            UserId = 6,
                            FullName = "Vũ Thị Quầy",
                            IsActive = true,
                            PasswordHash = "123456",
                            Role = "Cashier",
                            Username = "cashier04"
                        },
                        new
                        {
                            UserId = 7,
                            FullName = "Đỗ Bán Lẻ",
                            IsActive = true,
                            PasswordHash = "123456",
                            Role = "Cashier",
                            Username = "cashier05"
                        },
                        new
                        {
                            UserId = 8,
                            FullName = "Ngô Quản Kho",
                            IsActive = true,
                            PasswordHash = "123456",
                            Role = "Warehouse",
                            Username = "ware01"
                        },
                        new
                        {
                            UserId = 9,
                            FullName = "Bùi Kiểm Kê",
                            IsActive = true,
                            PasswordHash = "123456",
                            Role = "Warehouse",
                            Username = "ware02"
                        },
                        new
                        {
                            UserId = 10,
                            FullName = "Dương Thủ Kho",
                            IsActive = true,
                            PasswordHash = "123456",
                            Role = "Warehouse",
                            Username = "ware03"
                        },
                        new
                        {
                            UserId = 11,
                            FullName = "Lý Nhập Hàng",
                            IsActive = true,
                            PasswordHash = "123456",
                            Role = "Warehouse",
                            Username = "ware04"
                        },
                        new
                        {
                            UserId = 12,
                            FullName = "Đặng Hỗ Trợ",
                            IsActive = true,
                            PasswordHash = "123456",
                            Role = "Admin",
                            Username = "admin_backup"
                        },
                        new
                        {
                            UserId = 13,
                            FullName = "Hồ Ca Chiều",
                            IsActive = true,
                            PasswordHash = "123456",
                            Role = "Cashier",
                            Username = "cashier06"
                        },
                        new
                        {
                            UserId = 14,
                            FullName = "Trương Vận Chuyển",
                            IsActive = true,
                            PasswordHash = "123456",
                            Role = "Warehouse",
                            Username = "ware05"
                        },
                        new
                        {
                            UserId = 15,
                            FullName = "Mai Giám Sát",
                            IsActive = true,
                            PasswordHash = "123456",
                            Role = "Admin",
                            Username = "supervisor"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
